# App of Apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd  # ArgoCD's namespace
  # dependency, lowest priorty will be created first
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Trinath9395/eks-cluster-argocd.git
    targetRevision: main   # or a tag/commit hash
    path: namespaces        # folder in repo with Kubernetes YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true           # delete resources not in Git
      selfHeal: true        # revert out-of-band changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
