apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend
  namespace: expense  # Change to your namespace
spec:
  podSelector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
              tier: web
              project: expense
      ports:
        - protocol: TCP
          port: 8080
